version: '3.7'

networks:
  private:
    driver: bridge

services:
  # Database
  postgres:
    image: postgres:11.7-alpine
    volumes:
      - /var/opt/api_local/pg_data:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - private
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure

  # Grafana
#  grafana:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - ENV/grafana.env
#    volumes:
#      - ./ENV/grafana.ini:/etc/grafana/grafana.ini
#    depends_on:
#      - postgres
#    ports:
#      - "3001:3000"
#    networks:
#      - private
#    restart: on-failure
